# Generated by Django 5.2.4 on 2025-07-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, help_text="For scheduled bookings", null=True
                    ),
                ),
                (
                    "requested_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time the booking was requested"
                    ),
                ),
                ("address", models.TextField(help_text="Full address for the service")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Latitude,Longitude of service location if different from address",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled_by_customer", "Cancelled by Customer"),
                            ("cancelled_by_provider", "Cancelled by Provider"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, help_text="Notes from the customer"),
                ),
                (
                    "provider_notes",
                    models.TextField(blank=True, help_text="Notes from the provider"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-requested_time"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base rate for the service",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
            },
        ),
    ]
