# Generated by Django 5.2.4 on 2025-07-07 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_as_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="provider_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_as_provider",
                to="users.serviceproviderprofile",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="provider_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_offered",
                to="users.serviceproviderprofile",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
    ]
